### ISSUE TITLE
UUID error

### ISSUE THREAD

**Issue by tc** [tc/elastic-mapreduce-ruby#1]
./elastic-mapreduce --list
INFO Exception Retriable invalid response returned from DescribeJobFlows: {"Error"=>{"Details"=>#<NoMethodError: undefined method `random_create' for UUID:Class>, "Code"=>"InternalFailure", "Type"=>"Sender"}} while calling DescribeJobFlows on Amazon::Coral::ElasticMapReduceClient, retrying in 3.0 seconds.

**Comment by caspar2d** [comment]
I'm running into the same problem. It doesn't seem like there is a solution yet. Are there alternatives?

**Comment by tc** [comment]
fixed by using new uuid
https://github.com/tc/elastic-mapreduce-ruby/commit/ea4f8b86f617575144ae9fc952940d98b75aedfb
