### ISSUE TITLE
Would it be possible to add an ARCH parameter to the script?

### ISSUE THREAD

**Issue by mischat** [tc/elastic-mapreduce-ruby#4]
As it stands you can choose between i386 and x86 m1.small and m1.medium machines. Could you add a parameter to this script to allow a user to select the ARCH upon the creation of a new cluster?

Or you could tell me how to do it, and I could supply a patch.

Thanks!

**Comment by tc** [comment]
Hi, EMR is its down custom distro.

You can change the instance type though:

  $ elastic-mapreduce --create --alive --name "Testing PIG -- $USER" \
      --num-instances 5 --instance-type c1.large \
      --hive-interactive

**Comment by mischat** [comment]
Hiya, 

In EMR's console we have a choice between 32bit and 64bit m1.small and m1.medium machines. But I don't have that option when using your (awesome) ruby client.
