### ISSUE TITLE
warning: else without rescue is useless

### ISSUE THREAD

**Issue by wimrijnders** [tc/elastic-mapreduce-ruby#6]
Hi folks,

When trying to run ./elastic-mapreduce under ruby 1.9, I get the following:

```
elastic-mapreduce-cli/amazon/coral/httpdestinationhandler.rb:23: warning: else without rescue is useless
<internal:lib/rubygems/custom_require>:29:in `require': elastic-mapreduce-cli/amazon/coral/httpdestinationhandler.rb:19: syntax error, unexpected ':', expectingkeyword_then or ',' or ';' or '\n' (SyntaxError)
```

Now, I know the specs say that ruby 1.8.7 should be used, but I believe that it is possible to  make the script run on ruby 1.9 with minor modifications.

The reason for this error is that the ruby syntax changed from 1.8 to 1.9, see http://stackoverflow.com/questions/9305509/case-expression-different-in-ruby-1-9.

To make it work on 1.9 while keeping compatibility with 1.8, you need to convert all colons in when statements to the 'then' keyword, eg:

``` ruby
        @uri = case endpoint
               when URI then     # previously, ':' instead of 'then'
                   endpoint
               else
                 URI.parse(endpoint)
               end
```

If the when-statements are not on a single line (as in example above), you can in fact leave the 'then' out as well.

The places in the code to adjust like this are (line numbers approximate):

```
amazon/coral/httpdestinationhandler.rb:23
amazon/coral/querystringmap.rb:50
```

I scanned all case-statements in the rest of the code, these are all OK. So I think this was just an oversight.

**Comment by wimrijnders** [comment]
OK, on further inspection of the code on github, I see that this issue has been fixed in exactly the way I described.
Closing it. Now, I wish that Amazon updated its links in the documentation.

Will use this codebase now.

**Comment by tc** [comment]
Yea, I forked the amazon code for ruby 1.9.x comp. I tried to get amazon to pull the changes from this repo but they haven't yet.

**Comment by wimrijnders** [comment]
In any case thanks. It got me started one hell of a lot quicker than the amazon code. Cheers.

**Comment by paulbutcher** [comment]
I just got bitten by this, a year after this bug was reported and three (yes, three) years after @tc fixed the problem. Excellent work, Amazon. Excellent.
